openapi: 3.1.0
info:
  title: NFT API
  description: NFT API v3 Documentation.
  contact:
    name: Venly
    url: https://venly.io
    email: contact@venly.io
  version: 0.40.0
servers:
  - url: https://token-api-sandbox.venly.io/
    description: Sandbox Environment
  - url: https://token-api.venly.io/
    description: Production Environment
paths:
  /actuator/health:
    get:
      tags:
        - NFT-API Health
      summary: Check Health
      description: This endpoint is used to check the current health of the **NFT-API**. It returns the API health status as either **UP** or **DOWN**.
      operationId: healthCheckNftv3
      security:
        - OAuth2: []
  /api/v3/erc1155/chains:
    get:
      tags:
        - Get Supported Chains
      summary: Get Supported Chains
      description: This endpoint is used to retrieve the supported chains for the NFT API.
      operationId: getSupportedChainsErc1155
      security:
        - OAuth2: []
  /api/v3/wallets:
    get:
      tags:
        - Company Wallets
      summary: 'Get All Company Wallets'
      description: "This endpoint retrieves all company minter wallets."
      operationId: getCompanyWallets
      security:
        - OAuth2:
            - manage:minter-wallet
  /api/v3/wallets/{chain}:
    get:
      tags:
        - Company Wallets
      summary: 'Get Company Wallets by Chain'
      description: "This endpoint retrieves company minter wallets by blockchain."
      operationId: getCompanyWalletByChain_1
      security:
        - OAuth2:
            - manage:minter-wallet
  /api/v3/wallets/{chain}/{address}:
    delete:
      tags:
        - Company Wallets
      operationId: deleteMinterWallet
      summary: "Delete Company Wallet"
      description: "This endpoint deletes a company wallet by blockchain and wallet address."
      security:
        - OAuth2:
            - manage:minter-wallet
  /api/v3/erc1155/contracts:
    get:
      tags:
        - Contract
      summary: 'Get all contracts'
      description: "This endpoint fetches all of your contracts."
      operationId: getContracts
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/metadata:
    get:
      tags:
        - Contract Metadata
      summary: 'Get Contract Metadata'
      description: "This endpoint is used to fetch the metadata of as contract."
      operationId: getContractMetadata
      security:
        - OAuth2:
            - manage:contracts
    patch:
      tags:
        - Contract Metadata
      summary: 'Update Contract Metadata'
      description: "This endpoint is used to update the metadata of a contract."
      operationId: patchContractMetadata
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/token-types:
    get:
      tags:
        - Token-Types
      summary: 'Get All Token-types'
      operationId: getAllTokenTypes
      security:
        - OAuth2:
            - view:token-types
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/token-types/{tokenTypeId}/metadata:
    get:
      tags:
        - Token-Type Metadata
      summary: 'Get Token-type Metadata'
      description: "This endpoint is used to fetch the metadata of a token-type"
      operationId: getTokenMetadata_1
      security:
        - OAuth2:
            - view:token-types
    put:
      tags:
        - Token-Type Metadata
      summary: 'Update Token-type Metadata'
      description: "This endpoint is used to update the metadata of a token-type."
      operationId: updateMetadataForTokenType
      security:
        - OAuth2:
            - manage:token-types
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/tokens:
    get:
      tags:
        - Mint Tokens
      summary: 'Get All Tokens'
      description: "This endpoint is used to get all tokens in a contract."
      operationId: getTokens
      security:
        - OAuth2:
            - view:tokens
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/tokens/{tokenId}/metadata:
    get:
      tags:
        - Token Metadata
      summary: 'Get Token Metadata'
      description: "This endpoint fetches the metadata of a token by `tokenId`."
      operationId: getTokenMetadata
      security:
        - OAuth2:
            - view:tokens
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/tokens/{tokenId}/metadata/{propertyName}:
    put:
      tags:
        - Token Metadata
      summary: 'Update Property'
      description: "This endpoint is used to update a property for a specific NFT. You can also add a property using this endpoint."
      operationId: updatePropertyForToken
      security:
        - OAuth2:
            - manage:tokens
    delete:
      tags:
        - Token Metadata
      summary: 'Delete Property'
      description: "This endpoint is used to delete a property for a specific NFT."
      operationId: deletePropertyForToken
      security:
        - OAuth2:
            - manage:tokens
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/tokens/{tokenId}/metadata/attributes:
    post:
      tags:
        - Token Metadata
      summary: 'Add Attribute'
      description: "This endpoint is used to add attributes to a specific NFT."
      operationId: addAttributeForToken
      security:
        - OAuth2:
            - manage:tokens
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/tokens/{tokenId}/metadata/attributes/{attributeName}:
    put:
      tags:
        - Token Metadata
      summary: 'Update Attribute'
      description: "This endpoint is used to update an attribute's data for a specific NFT."
      operationId: updateAttributeForToken
      security:
        - OAuth2:
            - manage:tokens
    delete:
      tags:
        - Token Metadata
      summary: 'Delete Attribute'
      description: "This endpoint is used to delete an attribute for a specific NFT."
      operationId: deleteAttributeForToken
      security:
        - OAuth2:
            - manage:tokens
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/tokens/{tokenId}/metadata/animationUrls:
    put:
      tags:
        - Token Metadata
      summary: 'Update Animation URLs'
      description: "This endpoint is used to update the `animationUrls` for a specific NFT."
      operationId: updateAnimationUrlsMetadataForToken
      security:
        - OAuth2:
            - manage:tokens
    delete:
      tags:
        - Token Metadata
      summary: 'Delete Animation URLs'
      description: "This endpoint is used to delete `animationUrls` for a specific NFT."
      operationId: deleteAnimationUrlsMetadataForToken
      security:
        - OAuth2:
            - manage:tokens
  /api/v3/erc1155/tokens/mints:
    get:
      tags:
        - Mint Tokens
      summary: 'Get All Token Mints'
      description: "This endpoint is used to retrieve all of your token mint requests."
      operationId: getAll
      security:
        - OAuth2:
            - view:tokens
    post:
      tags:
        - Mint Tokens
      summary: 'Mint Tokens'
      description: "This endpoint is used to mint fungible or non-fungible tokens."
      operationId: mintTokens
      security:
        - OAuth2:
            - manage:tokens
  /api/v3/erc1155/token-types/creations:
    post:
      tags:
        - Token-Types
      summary: 'Create Token-type'
      description: "This endpoint is used to create a token-type."
      operationId: createTokenType
      security:
        - OAuth2:
            - manage:token-types
            - manage:tokens
  /api/v3/media:
    post:
      tags:
        - Media
      summary: 'Upload Media File'
      description: "This endpoint is used to upload a media file to our servers."
      operationId: addMedia
      security:
        - OAuth2:
            - upload:media
  /api/v3/images:
    post:
      tags:
        - Media
      summary: 'Upload Image'
      description: "This endpoint is used to upload an NFT image to our servers. Make sure to only upload images to with this endpoint."
      operationId: addNftImage
      security:
        - OAuth2:
            - upload:media
  /api/v3/erc1155/contracts/deployments:
    post:
      tags:
        - Contract
      summary: 'Create Contract'
      description: "This endpoint is used to create a contract."
      operationId: deployContract
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc1155/contracts/deployments/{deploymentId}:
    get:
      tags:
        - Contract
      summary: 'Check Contract Status'
      description: "This endpoint is used to check the status of the contract creation request."
      operationId: getContract_1
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/owner:
    put:
      tags:
        - Contract
      summary: 'Update Contract Owner'
      operationId: updateOwner
      description: "This endpoint is used to update the `owner` of an NFT contract. The updated owner will have admin rights on the contract."
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/royalties:
    put:
      tags:
        - Contract
      summary: 'Update Royalty for NFT Contract'
      description: "This endpoint is used to add/update the royalties for an NFT contract. You can add a royalty recipient wallet address and specifiy the royalty percentage. (_only for contracts created with the NFT v3_)"
      operationId: updateRoyalties
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc1155/tokens/mints/{mintId}:
    get:
      tags:
        - Mint Tokens
      summary: 'Check Token Mint Status'
      description: "This endpoint is used to check the status of a token mint request."
      operationId: getTokenMint
      security:
        - OAuth2:
            - view:tokens
  /api/v3/erc1155/token-types/creations/{creationId}:
    get:
      tags:
        - Token-Types
      summary: 'Check Token-type Status'
      description: "This endpoint is used to check the status of token-type creation request."
      operationId: getTokenType
      security:
        - OAuth2:
            - view:token-types
  /api/v3/erc1155/contracts/{chain}/{contractAddress}:
    get:
      tags:
        - Contract
      summary: 'Get Contract by Chain and Contract Address'
      description: "This endpoint is used to get a specific contract by blockchain and contract address."
      operationId: getContract
      security:
        - OAuth2:
            - manage:contracts
    delete:
      tags:
        - Contract
      summary: 'Archive Contract'
      description: "This endpoint allows you to archive a contract. When you archive an NFT contract, it will be removed from all API responses, rendering it inaccessible via any API calls. Furthermore, you will lose the ability to create new token-types under the deleted contract. All token-types and minted NFTs associated with the archived contract will also be archived and cannot be accessed via API calls. However, the NFT contract will remain on the blockchain."
      operationId: archiveTokenContract
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/tokens/{tokenId}:
    get:
      tags:
        - Mint Tokens
      summary: 'Get Specific Token Details'
      description: "This endpoint fetches the details of a specific token by tokenId."
      operationId: getToken
      security:
        - OAuth2:
            - view:tokens
    delete:
      tags:
        - Mint Tokens
      summary: 'Archive a Token'
      description: "This endpoint is used to archive a token by `tokenId`. The archived token will continue to exist on-chain but it will not be returned in API calls anymore."
      operationId: archiveToken
      security:
        - OAuth2:
            - manage:tokens
  /api/v3/erc1155/contracts/{chain}/{contractAddress}/token-types/{tokenTypeId}:
    get:
      tags:
        - Token-Types
      summary: 'Get Specific Token-type Details'
      description: "This endpoint fetches the details of a specific token-type by `tokenTypeId`."
      operationId: getTokenType_1
      security:
        - OAuth2:
            - view:token-types
    delete:
      tags:
        - Token-Types
      summary: 'Archive Token-type'
      description: "This endpoint archives a token type, removing it from all API responses and making it inaccessible through API calls. Once archived, you will no longer be able to mint new NFTs under this token type. Additionally, all NFTs associated with the archived token type will also be archived and cannot be accessed via API calls."
      operationId: archiveTokenType
      security:
        - OAuth2:
            - manage:token-types
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login-staging.venly.io/auth/realms/Arkane/protocol/openid-connect/token
          scopes:
            openid: openid
