openapi: 3.1.0
info:
  title: PAY API
  description: Venly Pay OA3.0 Documentation
  contact:
    name: Venly
    url: https://venly.io
    email: contact@venly.io
  version: 1.7.0
servers:
  - url: https://api-pay-sandbox.venly.io/
    description: Sandbox Environment
  - url: https://api-pay.venly.io/
    description: Production Environment
paths:
  /actuator/health:
    get:
      tags:
        - PAY-API Health
      summary: Check Health 
      description: This endpoint is used to check the current health of the **PAY-API**. It returns the API health status as either **UP** or **DOWN**.
      operationId: healthCheckPay
      security:
        - OAuth2: []
  /fiat-ramp/{provider}/currencies:
    get:
      tags:
        - Fiat On/Off Ramp
      summary: 'Get supported fiat and crypto currencies'
      description: 'Get all supported fiat currencies and crypto currencies for a specific provider. The response includes the `fiat` and `crypto` arrays. The `fiat[]` array includes all the supported fiat currencies for the specific provider, and the `crypto[]` array includes all the supported crypto currencies for the specific provider.'
      operationId: getCurrencies
      security:
        - OAuth2:
            - view:currencies
  /fiat-ramp/transak/on:
    post:
      tags:
        - Fiat On/Off Ramp
      summary: 'Transak Onramp'
      description: 'This endpoint is used to create a Transak onramp URL.'
      operationId: getTransakFiatOnRampUrl
      security:
        - OAuth2:
            - use:on-ramp
  /fiat-ramp/transak/off:
    post:
      tags:
        - Fiat On/Off Ramp
      summary: 'Transak Offramp'
      description: 'This endpoint is used to create a Transak offramp URL.'
      operationId: getTransakFiatOffRampUrl
      security:
        - OAuth2:
            - use:off-ramp
  /fiat-ramp/ramp-network/on:
    post:
      tags:
        - Fiat On/Off Ramp
      summary: 'Ramp Network Onramp'
      description: 'This endpoint is used to create a Ramp Network onramp URL.'
      operationId: getRampNetworkFiatOnRampUrl
      security:
        - OAuth2:
            - use:on-ramp
  /fiat-ramp/ramp-network/off:
    post:
      tags:
        - Fiat On/Off Ramp
      summary: 'Ramp Network Offramp'
      description: 'This endpoint is used to create a Ramp Network offramp URL.'
      operationId: getRampNetworkFiatOffRampUrl
      security:
        - OAuth2:
            - use:off-ramp
  /fiat-ramp/moonpay/on:
    post:
      tags:
        - Fiat On/Off Ramp
      summary: 'Moonpay Onramp'
      description: 'This endpoint is used to create a Moonpay onramp URL.'
      operationId: getMoonpayFiatOnRampUrl
      security:
        - OAuth2:
            - use:on-ramp
  /fiat-ramp/moonpay/off:
    post:
      tags:
        - Fiat On/Off Ramp
      summary: 'Moonpay Offramp'
      description: 'This endpoint is used to create a Moonpay offramp URL.'
      operationId: getMoonpayFiatOffRampUrl
      security:
        - OAuth2:
            - use:off-ramp
  /checkout/sessions:
    post:
      tags:
        - Checkout
      summary: 'Create Checkout Link'
      description: "Initiate the checkout process for a single payment by calling this endpoint. Save the `id` and `url` from response body. The `id` parameter is the sessionId (Used when checking status of this checkout), and the `url` parameter is the checkout URL (You pass this to your end-user)."
      operationId: checkoutSession
      security:
        - OAuth2:
            - create:checkout-session
  /account/settings/branding/icon:
    post:
      tags:
        - Checkout Branding
      operationId: uploadIcon
      summary: "Upload Icon"
      description: "Personalize your checkout page by adding your business' icon or logo. The icon must be a square image and have a minimum size of **128px x 128px**."
      security:
        - OAuth2: []
  /account/settings/branding:
    post:
      tags:
        - Checkout Branding
      operationId: updateSettingsBranding
      summary: "Customize Checkout Page"
      description: "You can select a primary color for the left side of the checkout page, and a secondary color for the PAY button. The checkout page will also feature your icon."
      security:
        - OAuth2: []        
  /stripe-dashboard:
    get:
      tags:
        - Stripe Dashboard
      operationId: getDashboardLink
      summary: "Get Stripe Dashboard Login Link"
      description: "This endpoint allows you to fetch a login link for your Stripe dashboard."
      security:
        - OAuth2: []
  /checkout/sessions/{sessionId}:
    get:
      tags:
        - Checkout
      summary: 'Get Checkout Status'
      description: "To retrieve the details of a completed or canceled checkout, call this endpoint using the corresponding session `ID`."
      operationId: getSession
      security:
        - OAuth2:
            - retrieve:checkout-session
  /webhooks:
    post:
      tags:
        - Webhooks
      summary: 'Create a Webhook'
      description: "This endpoint is used to create a webhook, to receive updates of your user's payments (_successful/cancelled_)."
      operationId: createWebhook
      security:
        - OAuth2:
            - manage:webhooks
    get:
      tags:
        - Webhooks
      summary: 'Get Webhooks'
      description: "This endpoint is used to get all of your webhooks."
      operationId: findAll
      security:
        - OAuth2:
            - manage:webhooks
  /webhooks/{webhookId}:
    put:
      tags:
        - Webhooks
      summary: 'Update a Webhook'
      operationId: update
      security:
        - OAuth2:
            - manage:webhooks
    delete:
      tags:
        - Webhooks
      summary: 'Delete a Webhook'
      operationId: delete
      security:
        - OAuth2:
            - manage:webhooks
  /checkout/sessions/{sessionId}/line_items:
    get:
      tags:
        - Checkout
      summary: 'Get Line Items'
      description: "This endpoint retrieves a checkout session's line items."
      operationId: getLineItems
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login-qa.arkane.network/auth/realms/Arkane/protocol/openid-connect/token
          scopes:
            openid: openid
