openapi: 3.1.0
info:
  title: Token API
  description: Token API v3 Dcumentation.
  contact:
    name: Venly
    url: https://venly.io
    email: contact@venly.io
  version: 0.33.0
servers:
  - url: https://token-api-sandbox.venly.io/
    description: Sandbox Environment
  - url: https://token-api.venly.io/
    description: Production Environment
paths:
  /actuator/health:
    get:
      tags:
        - Token-API Health
      summary: Check Health
      description: This endpoint is used to check the current health of the **NFT-API**. It returns the API health status as either **UP** or **DOWN**.
      operationId: healthCheckTokenApiV3
      security:
        - OAuth2: []
  /api/v3/erc20/chains:
    get:
      tags:
        - Get Supported Chains
      summary: Get Supported Chains
      description: This endpoint is used to retreive the supported chains for the Token API.
      operationId: getSupportedChainsErc20
      security:
        - OAuth2: []
  /api/v3/erc20/contracts/deployments:
    post:
      tags:
        - ERC20 Contract
      summary: 'Create contract'
      description: "This endpoint is used to create an ERC20 contract."
      operationId: deployErc20Contract
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc20/contracts/deployments/{deploymentId}:
    get:
      tags:
        - ERC20 Contract
      summary: 'Check token contract status'
      description: "This endpoint is used to check the status of the token contract creation request."
      operationId: getErc20ContractDeployment
      security:
        - OAuth2:
            - view:contracts
  /api/v3/erc20/tokens/mints:
    post:
      tags:
        - Mint ERC20 Tokens
      summary: 'Mint ERC20 tokens'
      description: "This endpoint is used to mint and send ERC20 tokens."
      operationId: mintErc20Tokens
      security:
        - OAuth2:
            - manage:tokens
    get:
      tags:
        - Mint ERC20 Tokens
      summary: 'Get All ERC20 Token Mints'
      description: 'This endpoint is used to retrieve all of your ERC20 token mint requests.'
      operationId: getAllErc20Mints
      security:
        - OAuth2:
            - view:tokens
  /api/v3/erc20/tokens/mints/{mintId}:
    get:
      tags:
        - Mint ERC20 Tokens
      summary: 'Check token mint status'
      description: "This endpoint is used to check the status of a token mint request."
      operationId: getErc20TokenMintStatus
      security:
        - OAuth2:
            - view:tokens
  /api/v3/erc20/contracts:
    get:
      tags:
        - ERC20 Contract
      summary: 'Get all contracts'
      description: "This endpoint fetches all of your token contracts."
      operationId: getAllErc20Contracts
      security:
        - OAuth2:
            - view:contracts
  /api/v3/erc20/contracts/{chain}/{contractAddress}:
    get:
      tags:
        - ERC20 Contract
      summary: 'Get contracts by chain and contract address'
      description: "This endpoint is used to get a specific token contract by blockchain and contract address."
      operationId: getErc20Contract
      security:
        - OAuth2:
            - view:contracts
    delete:
      tags:
        - ERC20 Contract
      summary: 'Archive Contract'
      description: "This endpoint allows you to archive an ERC20 contract. When you archive an ERC20 contract, it will be removed from all API responses, rendering it inaccessible via any API calls. Furthermore, you cannot mint new tokens under the archived contract. All minted ERC20 tokens associated with the archived contract will also be archived and cannot be accessed via API calls. However, the ERC20 contract will remain on the blockchain."
      operationId: archiveErc20TokenContract
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/erc20/contracts/{chain}/{contractAddress}/owner:
    put:
      tags:
        - ERC20 Contract
      summary: "Update token contract owner"
      description: "This endpoint is used to update the owner of a token contract."
      operationId: updateOwner
      security:
        - OAuth2:
            - manage:contracts
  /api/v3/wallets:
    get:
      tags:
        - Company Wallets
      summary: 'Get All Company Wallets'
      description: "This endpoint retrieves all company minter wallets."
      operationId: getCompanyWallets
      security:
        - OAuth2:
            - manage:minter-wallet
  /api/v3/wallets/{chain}:
    get:
      tags:
        - Company Wallets
      summary: 'Get Company Wallets by Chain'
      description: "This endpoint retrieves company minter wallets by blockchain."
      operationId: getCompanyWalletByChain_1
      security:
        - OAuth2:
            - manage:minter-wallet
  /api/v3/wallets/{chain}/{address}:
    delete:
      tags:
        - Company Wallets
      operationId: deleteMinterWallet
      summary: "Delete Company Wallet"
      description: "This endpoint deletes a company wallet by blockchain and wallet address."
      security:
        - OAuth2:
            - manage:minter-wallet
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: >-
            https://login-staging.venly.io/auth/realms/Arkane/protocol/openid-connect/token
          scopes:
            openid: openid