openapi: 3.1.0
info:
  title: Wallet API
  description: Wallet API Documentation.
  contact:
    name: Venly
    url: https://venly.io
    email: contact@venly.io
  version: 0.60.0
servers:
  - url: https://api-wallet-sandbox.venly.io/
    description: Sandbox Environment
  - url: https://api-wallet.venly.io/
    description: Production Environment
paths:
  /actuator/health:
    get:
      tags:
        - Wallet-API Health
      summary: Check Health 
      description: This endpoint is used to check the current health of the **Wallet-API**. It returns the API health status as either **UP** or **DOWN**.
      operationId: healthCheckWallet
      security:
        - OAuth2: []
  /api/users:
    get:
      tags:
        - User
      summary: 'Get all Users'
      description: "This endpoint retrieves all your users."
      operationId: getAll
      security:
        - OAuth2:
            - view:users
            - whitelabel
    post:
      tags:
        - User
      summary: 'Create User'
      description: "This endpoint is used to create a user."
      operationId: createUser
      security:
        - OAuth2:
            - create:users
            - whitelabel        
  /api/users/{userId}:
    get:
      tags:
        - User
      summary: 'Get User by ID'
      description: "This endpoint retrives the details of a user by their `userId`."
      operationId: getUser
      security:
        - OAuth2:
            - view:users
            - whitelabel
    put:
      tags:
        - User
      summary: 'Update User’s Reference'
      description: "This endpoint is used to update the reference of a user by `userId`."
      operationId: updateUser
      security:
        - OAuth2:
            - update:users
            - whitelabel
    delete:
      tags:
        - User
      summary: 'Delete User'
      description: "This endpoint deletes a user. All the linked wallets to the user will be inaccessible once the user has been deleted."
      operationId: deleteUser
      security:
        - OAuth2:
            - delete:users
            - whitelabel
  /api/users/{userId}/signing-methods:
    post:
      tags:
        - User
      summary: 'Create User’s Signing Method'
      description: "This endpoint allows you to create a signing method for a user, whether it's their first or an additional one. The first signing method must always be a six-digit `PIN`, and does not require the `Signing-Method` to be passed in the header. For creating subsequent signing methods like `BIOMETRIC`/`EMERGENCY_CODE`/`PASSWORD`, include an existing valid `Signing-Method` in the request header."
      operationId: createSigningMethod
      security:
        - OAuth2:
            - update:users
            - whitelabel
  /api/users/{userId}/signing-methods/{signingMethodId}:          
    put:
      tags:
        - User
      summary: 'Update User’s Signing Method'
      description: "This endpoint is used to update a user's signing method. This can be done, in case the user forgets their PIN. In order to update a signing method, another valid signign method has to be passed in the header."
      operationId: updateSigningMethod
      security:
        - OAuth2:
            - update:users
            - whitelabel
    delete:
      tags:
        - User
      summary: 'Delete User’s Signing Method'
      description: "This endpoint is used to delete a user's signing method."
      operationId: deleteSigningMethod
      security:
        - OAuth2:
            - update:users
            - whitelabel
  /api/wallets/{id}:
    get:
      tags:
        - Wallet
      summary: 'Get Wallet'
      description: "This endpoint gets a wallet by id."
      operationId: viewWallet
      security:
        - OAuth2:
            - view:wallets
            - manage:wallets
            - sign:wallets
            - whitelabel
  /api/wallets/{id}/metadata:
    patch:
      tags:
        - Wallet
      summary: 'Update Wallet'
      description: "This endpoint is used to update the wallet description and to archive or unarchive the wallet."
      operationId: updateMetadata_1
      security:
        - OAuth2:
            - manage:wallets
            - whitelabel            
  /api/wallets:
    get:
      tags:
        - Wallet
      summary: 'Get all Wallets'
      description: "This endpoint gets all wallets."
      operationId: viewWallets_1
      security:
        - OAuth2:
            - view:wallets
            - manage:wallets
            - sign:wallets
            - whitelabel
    post:
      tags:
        - Wallet
      summary: 'Create Wallet'
      description: "This endpoint is used to create a wallet."
      operationId: createWallet
      security:
        - OAuth2:
            - ARKANE_ONLY
            - manage:wallets
            - whitelabel                  
  /api/wallets/{walletId}/export:
    post:
      tags:
        - Wallet
      summary: "Export Wallet"
      description: "Please note that exporting a password-secured keystore enhances protection against man-in-the-middle attacks. We do not allow exporting of private keys by default due to associated risks. Exporting a wallet means the private key, granting access to the wallet, is beyond our control. If this key is compromised, it can be misused, leading to unauthorized access and potential loss. Enabling this feature in production carries significant risks, and caution is advised."
      operationId: exportById
      security:
        - OAuth2:
            - export:wallets
  /api/wallets/import:
    post:
      tags:
        - Wallet
      summary: 'Import Wallet'
      description: "This endpoint is used to import a wallet. Read more about [how to import a wallet](https://docs.venly.io/docs/import-a-wallet)."
      operationId: importWallet
      security:
        - OAuth2:
            - manage:wallets
            - whitelabel
  /api/wallets/address/validation/{secretType}/{walletAddress}:
    get:
      tags:
        - Wallet
      operationId: validateAddress
      summary: "Validate Wallet Address"
      description: "This endpoint is used to validate whether the format of a wallet address is correct for a specific chain."
      security:
        - OAuth2: []
  /api/wallets/{walletId}/events:
    get:
      tags:
        - Wallet
      operationId: index
      summary: "Get all Wallet Events"
      description: "This endpoint retrieves all the events related to a wallet by `walletId`. The events can be wallet created, funds transfer, signed signature, etc."
      security:
        - OAuth2: []
  /api/wallets/{walletId}/balance:
    get:
      tags:
        - Balance
      operationId: viewBalance
      summary: "Get native Balance by walletId"
      description: "This endpoint gets native balance of a wallet by wallet `ID`."
      security:
        - OAuth2: []
  /api/wallets/{walletId}/balance/tokens:
    get:
      tags:
        - Balance
      operationId: viewTokenBalances
      summary: " Get all ERC20 Token Balance by walletId"
      description: "This endpoint fetches all the ERC20 token balance by wallet `ID`"
      security:
        - OAuth2: []
  /api/wallets/{walletId}/balance/tokens/{token}:
    get:
      tags:
        - Balance
      operationId: viewTokenBalance
      summary: "Get specific ERC20 Token Balance by walletId and token address"
      description: "This endpoint retrieves ERC 20 Token balances by wallet `ID` and token contract address."
      security:
        - OAuth2: []
  /api/wallets/{secretType}/{walletAddress}/tokens/associations:
    get:
      tags:
        - Balance
      operationId: getTokenAssociations
      summary: " Get Token Associations for Hedera Wallet"
      description: "This endpoint retrieves the token assocciations for a Hedera wallet using the wallet address."
      security:
        - OAuth2: []
  /api/wallets/{secretType}/{walletAddress}/balance:
    get:
      tags:
        - Balance
      operationId: viewBalance_1
      summary: "Get native Balance by Chain and Wallet Address"
      description: "This endpoint gets the native balance by blockchain and wallet address."
      security:
        - OAuth2: []
  /api/wallets/{secretType}/{walletAddress}/balance/tokens:
    get:
      tags:
        - Balance
      operationId: viewTokenBalances_1
      summary: "Get ERC20 Balance by Chain and Wallet Address"
      description: "This endpoint is used to fetch ERC20 Token balance by blockchain and wallet address."
      security:
        - OAuth2: []
  /api/wallets/{secretType}/{walletAddress}/balance/tokens/{token}:
    get:
      tags:
        - Balance
      operationId: viewTokenBalance_1
      summary: "Get specific ERC20 Token Balance by Chain, Wallet Address, and Token Address"
      description: "This endpoint gets the ERC20 token balance by Wallet `ID`, wallet address, and token address. "
      security:
        - OAuth2: []
  /api/transactions:
    get:
      tags:
        - Transactions
      summary: "Get all Transactions"
      description: "This endpoint retrieves all your transactions, further you can filter them by the transaction status and by your users."  
      operationId: getAll_1
      security:
        - OAuth2: []
  /api/transactions/execute:
    post:
      tags:
        - Transactions
      summary: 'Execute Transaction'
      description: "This endpoint is used to create and execute any type of transaction. You need to provide the pincode in request body or the signing method in the header. You can execute any transaction such as NFT transfer, native transfer, ERC 20, etc."
      operationId: executeTransaction_1
      security:
        - OAuth2:
            - sign:wallets
  /api/transactions/prepare:
    post:
      tags:
        - Transactions
      summary: 'Prepare Transaction for Specific Chain'
      description: "This endpoint is used to prepare a transaction for a specific chain. It populates the transaction with gas fields and nonce. The gas fileds include the gas price / gas fee, so you can know the  potential cost of a transaction before actually submitting it. The response body can be directly submitted to the [execute transaction endpoint](https://docs.venly.io/reference/executetransaction_1)."
      operationId: prepareTransaction
      security:
        - OAuth2:
            - sign:wallets
  /api/transactions/build:
    post:
      tags:
        - Transactions
      summary: 'Get gas fee for a specific tx'
      description: "This endpoint is used to get the gas fee for a specific transaction, for example a native token transfer, ERC20 transfer, and NFT transfer. The response body includes the gass fee params for the specific transaction."
      operationId: buildTransaction
      security:
        - OAuth2:
            - sign:wallets
  /api/transactions/{secretType}/{transactionHash}/status:
    get:
      tags:
        - Transactions
      operationId: getStatus
      summary: "Get Transaction Status"
      description: "This endpoint retrieves the status of a specific transaction by chain and transaction hash. Returns `UNKNOWN` when the specific chain is not supported yet."
      security:
        - OAuth2: []
  /api/transactions/{secretType}/fees:
    get:
      tags:
        - Transactions
      operationId: getStatus_1
      summary: "Get Gas Price for a Chain"
      description: "This endpoint fetches the current fees (for EVM based chains: `gasprice`) for a specific chain"
      security:
        - OAuth2: []
  /api/signatures:
    get:
      tags:
        - Signatures
      operationId: getUserSignatureRequests
      summary: "Get Signature Request by userId"
      description: "This endpoint retrives all the signature requests, and the results can be filtered by `userId` and signature status."
      security:
        - OAuth2: []
    post:
      tags:
        - Signatures
      summary: 'Create and Sign Signature'
      description: "The signatures endpoint supports the EIP-712 standard, Ethereum typed structured data hashing and signing. This EIP aims to improve the usability of off-chain message signing for use on-chain."
      operationId: signTransaction
      security:
        - OAuth2:
            - sign:wallets
            - save:signature
  /api/signatures/prepare:
    post:
      tags:
        - Signatures
      summary: 'Prepare Signature'
      description: "This endpoint is used to prepare a signature with the status as **SAVED**. In case of a transaction signature, the endpoint will populate it with the required gas fields."
      operationId: prepareSignTransaction
      security:
        - OAuth2:
            - sign:wallets
  /api/signatures/{id}/confirm:
    post:
      tags:
        - Signatures
      operationId: confirmSignatureRequest
      summary: "Confirm Signature"
      description: "This endpoint is used to confirm a signature. This will change the status of the signature from **SAVED** to **READY**, which means it is ready to be signed. In case of a transaction signature, this endpoint will populate all the required gas fields."
      security:
        - OAuth2: []
  /api/signatures/{id}/sign:
    post:
      tags:
        - Signatures
      summary: 'Sign Signature'
      description: "This endpoint is used to sign a signature by `ID`."
      operationId: signSignatureRequest
      security:
        - OAuth2:
            - sign:wallets
  /api/signatures/build:
    post:
      tags:
        - Signatures
      operationId: buildSignature
      summary: "Build Signature Request"
      description: "This endpoint converts a generic signature request into a chain-specific signature request."
      security:
        - OAuth2: []
  /api/signatures/verification:
    post:
      tags:
        - Signatures
      operationId: isValidSignature
      summary: "Verify Signed Signature"
      description: "This endpoint verifies if a signature was signed by a specific wallet."
      security:
        - OAuth2: []
  /api/signatures/{id}:
    get:
      tags:
        - Signatures
      operationId: getSignatureRequestById
      summary: "Get Signature Request by id"
      description: "This endpoint retrives a signature by `ID`."
      security:
        - OAuth2: []
    delete:
      tags:
        - Signatures
      operationId: cancel_2
      summary: "Delete Signature Request by id"
      description: "This endpoint deletes a signature by `ID`."
      security:
        - OAuth2: []                 
  /api/transactions/resubmit:
    post:
      tags:
        - Transactions
      summary: 'Resubmit Transaction'
      description: "This endpoint immediately tries to resubmit a stuck transaction. Sometimes a transaction fails to execute/propagate. This can be due to several factors, for example, the gas price is too low."
      operationId: resubmit
      security:
        - OAuth2:
            - sign:wallets
  /api/transactions/cancel:
    post:
      tags:
        - Transactions
      summary: 'Cancel Transaction'
      description: "This endpoint immediately tries to cancel a stuck transaction."
      operationId: cancel
      security:
        - OAuth2:
            - sign:wallets
  /api/contracts/read:
    post:
      tags:
        - Contract
      operationId: readContract
      summary: "Read Contract"
      description: "This endpoint allows you to read contract functions. This function is only available for EVM-based chains."
      security:
        - OAuth2: []
  /api/contracts/abi/encode:
    post:
      tags:
        - contract
      operationId: encode
      summary: "Encode Inputs"
      description: "This endpoint allows you to encode contract functions. This function is only available for EVM-based chains."
      security:
        - OAuth2: []
  /api/contracts/abi/decode:
    post:
      tags:
        - contract
      operationId: decode
      summary: "Decode Inputs"
      description: "This endpoint allows you to decode contract functions. This function is only available for EVM-based chains."
      security:
        - OAuth2: []
  /api/wallets/{id}/user:
    put:
      tags:
        - Wallet
      summary: 'Link Wallet to User'
      description: "This endpoint is used only when migrating from the old/deprecated wallet management to the new user management. Click [here](https://docs.venly.io/docs/user-management) to read more about user management. It is used to link an existing wallet to a user."
      operationId: linkWalletToUser
      deprecated: true
      security:
        - OAuth2:
            - manage:users
            - whitelabel      
  /api/wallets/{id}/security:
    patch:
      tags:
        - Wallet
      summary: "Update Wallet PIN code"
      description: "This endpoint has been deprecated. Please click here to read about [Signing Methods](https://docs.venly.io/docs/signing-methods-api-flow)."
      operationId: updateSecurity
      deprecated: true
      security:
        - OAuth2:
            - manage:wallets
            - whitelabel
  /api/wallets/{walletId}/nonfungibles:
    get:
      tags:
        - Non-Fungibles
      operationId: listNonFungibles
      summary: "Get NFTs by walletId"
      description: "This endpoint retrieves NFTs by wallet `ID`"
      security:
        - OAuth2:
            - filter:nsfw 
  /api/wallets/nonfungibles:
    get:
      tags:
        - Non-Fungibles
      operationId: listNonFungibles_1
      summary: "Get NFTs by Chain"
      description: "This endpoint retrieves NFTs by blockchain."
      security:
        - OAuth2:
            - filter:nsfw
  /api/wallets/{secretType}/{walletAddress}/nonfungibles:
    get:
      tags:
        - Non-Fungibles
      operationId: listNonFungiblesByAddress
      summary: "Get NFTs by Chain and Wallet Address"
      description: "This endpoint retrieves NFTs by blockchain and wallet address."
      security:
        - OAuth2:
            - filter:nsfw
  /api/nonfungibles/{secretType}/{contractAddress}:
    get:
      tags:
        - Non-Fungibles
      operationId: getNonFungibleContract
      summary: "Get NFT contract"
      description: "This endpoint retrieves NFT contract information by blockchain and contract address."
      security:
        - OAuth2: []
  /api/nonfungibles/{secretType}/{contractAddress}/{tokenId}:
    get:
      tags:
        - Non-Fungibles
      operationId: getNonFungible
      summary: "Get NFT information"
      description: "This endpoint retrieves a specific NFT information by chain, contract address, and the token `ID`."
      security:
        - OAuth2: []
  /api/nonfungibles/{secretType}/{contractAddress}/{tokenId}/wallets:
    get:
      tags:
        - Non-Fungibles
      summary: 'Get Wallets that contain specific NFTs'
      description: "This endpoint fetches the wallet that contain a specific NFT. The wallets are filtered by blockchain, contract address of the NFT, and the token `ID`"
      operationId: getTokenWalletBalance
      security:
        - OAuth2:
            - view:wallet-analytics
  /api/wallets/HEDERA/{walletAddress}/nonfungibles/allowances:
    get:
      tags:
        - Non-Fungibles
      operationId: getHederaNonfungibleAllowances
      summary: "Get Token Allowances for Hedera NFTs"
      description: "This endpoint retrieves the token allowances specifically for Hedera chain"
      security:
        - OAuth2: []
  /api/contracts/{secretType}/{address}/wallets:
    get:
      tags:
        - Non-Fungibles
      summary: 'Get Wallets that contain NFT from a specific Contract'
      description: "This endpoint returns the wallet address(es) which contain NFTs from a specific NFT contract address."
      operationId: getWalletBalance
      security:
        - OAuth2:
            - view:wallet-analytics
  /api/wallets/{id}/swaps/pairs:
    get:
      tags:
        - Token Swapping
      summary: 'Get Token Pairs'
      description: "This endpoint gets all the possible token pairs that can be swapped based on the blockchain of the wallet."
      operationId: getTradingPairs
      security:
        - OAuth2:
            - use:swaps
  /api/swaps/rates:
    get:
      tags:
        - Token Swapping
      summary: 'Get Exchange Rate'
      description: "This endpoint returns information about the expected result of the swap. It provides the expected output amount, as well gives information about the slippage, and fee involved for that specific swap."
      operationId: getExchangeRate
      security:
        - OAuth2:
            - use:swaps       
  /api/wallets/{id}/swaps:
    post:
      tags:
        - Token Swapping
      summary: 'Build Swap'
      description: "This endpoint returns the transaction detail that is needed to perform the actual swap, based on information obtained in the **Get Exchange Rate** endpoint. This endpoint will build a transaction for you, which afterward you or your user needs to execute. Each item in the response array needs to be taken, enriched with the relevant signing method and submitted against the endpoint: `/api/transactions/execute`"
      operationId: createSwap
      security:
        - OAuth2:
            - use:swaps
  /api/chains/{secretType}:
    get:
      tags:
        - Chain
      operationId: getBlockchainBlock
      summary: "Get Block information by Chain"
      description: "This endpoint returns the block information of a chain."
      security:
        - OAuth2: []
  /api/chains:
    get:
      tags:
        - Chain
      operationId: secretTypes_1
      summary: "Get all supported Chains"
      description: "This endpoint returns all the supported chains by the Wallet-API."
      security:
        - OAuth2: []
  /api/security:
    get:
      tags:
        - Security Endpoint
      operationId: getKeys
      summary: "Get Venly Public Key"
      description: "This endpoint retrieves the Venly public key."
      security:
        - OAuth2: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login-staging.venly.io/auth/realms/Arkane/protocol/openid-connect/token
          scopes:
            openid: openid
    Signing-Method:
      type: apiKey
      description: A valid signing method for the user. The format should be id:value
      name: Signing-Method
      in: header
    Encrypted-Signing-Method:
      type: apiKey
      description: "Use this for encrypted PIN transfers. The `Encrypted-Signing-Method` indicates that the signing method and the request body are encrypted. Click [here](https://docs.venly.io/docs/encrypted-pin-transfer) to read about encrypted PIN transfers."
      name: Encrypted-Signing-Method
      in: header
